window (new | open): app.window_open()
window next: app.window_next()
window last: app.window_previous()
window close: app.window_close()
window hide: app.window_hide()
# following only works on windows. Can't figure out how to make it work for mac. No idea what the equivalent for linux would be.
focus$: user.switcher_menu()
focus next: key("alt-tab")
focus chat: user.switcher_focus_window_by_title("Brave", "Google Chat")
focus brave: user.switcher_focus_window_by_title("Brave", "Brave")
focus reminders: user.switcher_focus_window_by_title("Outlook", "Reminder")
focus teams: user.switcher_focus_window_by_title("Teams", "Microsoft Teams")
focus g mail: user.switcher_focus_window_by_title("Edge", "Gmail")
focus edge Personal: user.switcher_focus_window_by_title("Edge", "Personal")
focus [work] edge [work]: user.switcher_focus_window_by_title("Edge", "Work")
focus bing chat: user.switcher_focus_window_by_title("Edge", "Bing AI")
focus (chat) G P T: user.switcher_focus_window_by_title("Edge", "ChatGPT")
focus outlook: user.switcher_focus_window_by_title("Outlook", "Inbox")
focus <user.running_applications>: user.switcher_focus(running_applications)
focus fix: 
    key("alt-tab")
    key("alt-tab")
running list: user.switcher_toggle_running()
running close: user.switcher_hide_running()
launch <user.launch_applications>: user.switcher_launch(launch_applications)

snap <user.window_snap_position>: user.snap_window(window_snap_position)
snap next [screen]: user.move_window_next_screen()
snap last [screen]: user.move_window_previous_screen()
snap screen <number>: user.move_window_to_screen(number)
snap <user.running_applications> <user.window_snap_position>:
    user.snap_app(running_applications, window_snap_position)
snap <user.running_applications> [screen] <number>:
    user.move_app_to_screen(running_applications, number)
